[project]
name = "Anas_bellaouali_workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "folium>=0.19.5",
    "matplotlib>=3.10.1",
    "numpy>=2.2.5",
    "pandas>=2.2.3",
    "streamlit-folium>=0.25.0",
    "streamlit>=1.44.1",
]
